### ISSUE TITLE
Encrypt without fingerprint authentication

### ISSUE THREAD

**Issue by nksaroj** [Mauin/RxFingerprint#26]
I am getting the token from the backend I am looking to encrypt it using this library and store it in SharedPrefrence and on subsequent Logon I would like to read the encrypted token from the shared preference and decrypt using the Fingerprint and send the decrypted token to backend 
It would be great if you could show some lights

**Comment by Mauin** [comment]
In your given example this would be done by calling `RxFingerprint.encrypt(context, "your_key_name", <token you received from your backend>)`. The user has to then touch the fingerprint sensor and you should display some UI that tells him to do so.

In the `onNext` of the resulting subscription you will then receive a result from which you can retrieve the encrypted value. You can store this value in the SharedPreferences.

When you later want to decrypt this value you call `RxFingerprint.decrypt(context, "your_key_name", <encrypted token from SharedPreference>)` which the user has to again confirm with his fingerprint. This will return you the decrypted token which you can then use for your backend.

You can see more detailed code examples in the sample.

**Comment by nksaroj** [comment]
Thanks mate. Can I able to generate the encrypted token without asking the user to touch on fingerprint during enablement process?

**Comment by Mauin** [comment]
Not with the way RxFingerprint is currently set up. I might figure out a way to add this in the future.

**Comment by petrdvorak** [comment]
@Mauin IMO this is not possible on Android. Unlike on iOS, where you can store keys to Keychain without Touch ID and only retrieval requires Touch ID, the key generation on Android requires fingerprint authentication to generate the encryption key.

When I was trying to accomplish this, the `SecretKey` object was not properly initialized when I was calling `keyGenerator.generateKey()` without prior fingerprint authentication...

**Comment by AKiniyalocts** [comment]
I am facing a related issue. Once fingerprint authentication is enabled in our application, we request a new cookie from the server, that cookie is then encrypted via 

`RxFingerprint.encrypt(this, KEY, loginCookie)`

That encrypted cookie is then persisted.

Then, when authentication is needed because of cookie expiration, user authentication is required and the cookie is decrypted via:

`RxFingerprint.decrypt(this, KEY, encryptedCookie)`

Once decrypted, we perform our login request with this unencrypted cookie. Upon a response from that login, a new login cookie is returned, so we prompt the user again for authentication to encrypt the cookie via:

`RxFingerprint.encrypt(this, KEY, loginCookie)`

I'm wondering if we can leverage [setUserAuthenticationValidityDurationSeconds()](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder.html#setUserAuthenticationValidityDurationSeconds(int)) inside of `KeyGenParameterSpec.Builder`
 to not require fingerprint authentication from the user if each encryption/decryption request falls within that set window.

**Comment by Mauin** [comment]
@AKiniyalocts That sounds interesting. I'd definitely be up for opening up the `KeyGenParameterSpec` a bit to make use cases like yours possible. 

I'll take a closer look at it on the weekend if I find a way to make this easily possible without changing the API of the library too much.
